[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.2.11",
    "anthropic>=0.49.0",
    "flask>=3.1.0",
    "openai>=1.70.0",
]
